version: "3"
services:
  api:
    image: medicine_api
    ports:
      - 3333:3333
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.2
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=medicine